In [22]:
import sqlite3
import pandas as pd

db_path = "/Users/zacurbiztondo/literary-analysis/data/interim/books.db"
conn = sqlite3.connect(db_path)

summary = pd.read_sql_query("""
SELECT
  (SELECT COUNT(*) FROM nyt_entries) AS nyt_rows,
  (SELECT MIN(published_date) FROM nyt_entries) AS min_date,
  (SELECT MAX(published_date) FROM nyt_entries) AS max_date,
  (SELECT COUNT(DISTINCT published_date) FROM nyt_entries) AS weeks,
  (SELECT COUNT(DISTINCT list_name) FROM nyt_entries) AS list_types,
  (SELECT COUNT(*) FROM books) AS books_rows
""", conn)

summary

   nyt_rows    min_date    max_date  weeks  list_types  books_rows
0       230  2024-01-07  2024-01-07      1          18           0

In [26]:
pd.read_sql_query("""
    SELECT DISTINCT list_name
    FROM nyt_entries
    """, conn)

                             list_name
0       Advice, How-To & Miscellaneous
1                        Audio Fiction
2                     Audio Nonfiction
3                             Business
4      Children’s & Young Adult Series
5    Children’s Middle Grade Hardcover
6             Children’s Picture Books
7      Combined Print & E-Book Fiction
8   Combined Print & E-Book Nonfiction
9              Graphic Books and Manga
10                   Hardcover Fiction
11                Hardcover Nonfiction
12                         Mass Market
13              Middle Grade Paperback
14                Paperback Nonfiction
15             Paperback Trade Fiction
16               Young Adult Hardcover
17               Young Adult Paperback

In [29]:
pd.read_sql_query("""
    SELECT *
    FROM nyt_entries LIMIT 30
    """, conn)

,id,list_name,published_date,rank,weeks_on_list,title,author,publisher,isbn13,isbn10,description,created_at
0,1,Combined Print & E-Book Fiction,2024-01-07,1,34,FOURTH WING,Rebecca Yarros,Red Tower,9781649374042,,Violet Sorrengail is urged by the commanding g...,2026-02-21 23:17:54
1,2,Combined Print & E-Book Fiction,2024-01-07,2,7,IRON FLAME,Rebecca Yarros,Red Tower,9781649374172,,The second book in the Empyrean series. Violet...,2026-02-21 23:17:54
2,3,Combined Print & E-Book Fiction,2024-01-07,3,8,THE HEAVEN & EARTH GROCERY STORE,James McBride,Riverhead,9780593422946,,Secrets held by the residents of a dilapidated...,2026-02-21 23:17:54
3,4,Combined Print & E-Book Fiction,2024-01-07,4,10,THE EXCHANGE,John Grisham,Doubleday,9780385548953,,"In a sequel to “The Firm,” Mitch McDeere, who ...",2026-02-21 23:17:54
4,5,Combined Print & E-Book Fiction,2024-01-07,5,27,ICEBREAKER,Hannah Grace,Atria,9781668026038,,Anastasia might need the help of the captain o...,2026-02-21 23:17:54
5,6,Combined Print & E-Book Fiction,2024-01-07,6,59,LESSONS IN CHEMISTRY,Bonnie Garmus,Doubleday,9780385547345,,A scientist and single mother living in Califo...,2026-02-21 23:17:54
6,7,Combined Print & E-Book Fiction,2024-01-07,7,14,HOLLY,Stephen King,Scribner,9781668016138,,The private detective Holly Gibney investigate...,2026-02-21 23:17:54
7,8,Combined Print & E-Book Fiction,2024-01-07,8,6,THE LITTLE LIAR,Mitch Albom,Harper,9780062406651,,The actions of an 11-year-old boy help facilit...,2026-02-21 23:17:54
8,9,Combined Print & E-Book Fiction,2024-01-07,9,6,THE EDGE,David Baldacci,Grand Central,9781538719916,,The second book in the 6:20 Man series. Travis...,2026-02-21 23:17:54
9,10,Combined Print & E-Book Fiction,2024-01-07,10,113,THE SEVEN HUSBANDS OF EVELYN HUGO,Taylor Jenkins Reid,Washington Square/Atria,9781501161933,,A movie icon recounts stories of her loves and...,2026-02-21 23:17:54
10,11,Combined Print & E-Book Fiction,2024-01-07,11,91,ALL THE LIGHT WE CANNOT SEE,Anthony Doerr,Scribner,9781501173219,,The lives of a blind French girl and a gadget-...,2026-02-21 23:17:54
11,12,Combined Print & E-Book Fiction,2024-01-07,12,5,ALEX CROSS MUST DIE,James Patterson,"Little, Brown",9780316402484,,The 32nd book in the Alex Cross series. When a...,2026-02-21 23:17:54
12,13,Combined Print & E-Book Fiction,2024-01-07,13,27,THE HOUSEMAID,Freida McFadden,Grand Central,9781538742570,,Troubles surface when a woman looking to make ...,2026-02-21 23:17:54
13,14,Combined Print & E-Book Fiction,2024-01-07,14,5,TWISTED LOVE,Ana Huang,Bloom,9781728274867,,The first book in the Twisted series. Secrets ...,2026-02-21 23:17:54
14,15,Combined Print & E-Book Fiction,2024-01-07,15,118,IT ENDS WITH US,Colleen Hoover,Atria,9781501110368,,A battered wife raised in a violent home attem...,2026-02-21 23:17:54
15,31,Combined Print & E-Book Nonfiction,2024-01-07,1,35,THE WAGER,David Grann,Doubleday,9780385534260,,The survivors of a shipwrecked British vessel ...,2026-02-22 03:36:38
16,32,Combined Print & E-Book Nonfiction,2024-01-07,2,3,OATH AND HONOR,Liz Cheney,"Little, Brown",9780316572064,,The former congresswoman from Wyoming recounts...,2026-02-22 03:36:38
17,33,Combined Print & E-Book Nonfiction,2024-01-07,3,9,THE WOMAN IN ME,Britney Spears,Gallery,9781668009048,,The Grammy Award-winning pop star details her ...,2026-02-22 03:36:38
18,34,Combined Print & E-Book Nonfiction,2024-01-07,4,108,KILLERS OF THE FLOWER MOON,David Grann,Vintage,9780307742483,,The story of a murder spree in 1920s Oklahoma ...,2026-02-22 03:36:38
19,35,Combined Print & E-Book Nonfiction,2024-01-07,5,124,THE BOYS IN THE BOAT,Daniel James Brown,Penguin,9780143125471,,The story of the American rowers who pursued g...,2026-02-22 03:36:38
20,36,Combined Print & E-Book Nonfiction,2024-01-07,6,7,MY NAME IS BARBRA,Barbra Streisand,Viking,9780525429524,,The EGOT winner chronicles her journey in show...,2026-02-22 03:36:38
21,37,Combined Print & E-Book Nonfiction,2024-01-07,7,24,"FRIENDS, LOVERS, AND THE BIG TERRIBLE THING",Matthew Perry,Flatiron,9781250866448,,"The late actor, known for playing Chandler Bin...",2026-02-22 03:36:38
22,38,Combined Print & E-Book Nonfiction,2024-01-07,8,15,ELON MUSK,Walter Isaacson,Simon & Schuster,9781982181284,,The author of “The Code Breaker” traces Musk’s...,2026-02-22 03:36:38
23,39,Combined Print & E-Book Nonfiction,2024-01-07,9,10,PREQUEL,Rachel Maddow,Crown,9780593444511,,The MSNBC host and co-author of “Bag Man” deta...,2026-02-22 03:36:38
24,40,Combined Print & E-Book Nonfiction,2024-01-07,10,39,OUTLIVE,Peter Attia with Bill Gifford,Harmony,9780593236598,,A look at recent scientific research on aging ...,2026-02-22 03:36:38
25,41,Combined Print & E-Book Nonfiction,2024-01-07,11,26,THE STORYTELLER,Dave Grohl,Dey Street,9780063076105,,A memoir by the musician known for his work wi...,2026-02-22 03:36:38
26,42,Combined Print & E-Book Nonfiction,2024-01-07,12,6,BEHIND THE SEAMS,Dolly Parton with Holly George-Warren,Ten Speed,9781984862129,,The country music legend shares stories about ...,2026-02-22 03:36:38
27,43,Combined Print & E-Book Nonfiction,2024-01-07,13,173,THE BODY KEEPS THE SCORE,Bessel van der Kolk,Penguin,9780143127741,,"How trauma affects the body and mind, and inno...",2026-02-22 03:36:38
28,44,Combined Print & E-Book Nonfiction,2024-01-07,14,6,GHOSTS OF HONOLULU,Mark Harmon and Leon Carroll Jr,Harper Select,9781400337019,,The story of a Japanese American naval intelli...,2026-02-22 03:36:38
29,45,Combined Print & E-Book Nonfiction,2024-01-07,15,14,AMERICAN PROMETHEUS,Kai Bird and Martin J. Sherwin,Vintage,9780375726262,,A biography of J. Robert Oppenheimer. Winner o...,2026-02-22 03:36:38

In [30]:
conn.close()