In [ ]:
from pathlib import Path
import sqlite3
import pandas as pd

DB_PATH = Path("../data/interim/books.db") 
DB_PATH.exists(), DB_PATH

(True, PosixPath('../data/interim/books.db'))

In [4]:
conn=sqlite3.connect(DB_PATH)

tables = pd.read_sql("""
    SELECT name
    FROM sqlite_master
    WHERE type='table';
    """, conn)

tables

              name
0      nyt_entries
1  sqlite_sequence
2            books
3           awards

In [5]:
pd.read_sql("""
    SELECT *
    FROM books
    """, conn)

Empty DataFrame
Columns: [id, key, title, author_names, first_publish_year, language_codes, isbn13, isbn10, subjects, description, last_enriched_at]
Index: []

In [6]:
conn.close()